### ISSUE TITLE
As a user, I can select filters of the type of person I want to date.

### ISSUE THREAD

**Issue by secdevyc** [jvela924/dating-app#2]
Checklist

**Comment by secdevyc** [comment]
- [ ] create get route 
- [ ] create post route
- [ ] create delete route
- [ ] create put route

**Comment by secdevyc** [comment]
@winslowdev  @hyosung11  @jvela924 @cquiett 

updated issue

**Comment by secdevyc** [comment]
Create delete route @hyosung11

**Comment by jvela924** [comment]
> @winslowdev @hyosung11 @jvela924 @cquiett
> 
> updated issue
